Numpy ( numerical py ) is a python package for scientific computation. It provides user with :
- Powerful N-dimensional array object
- Sophisticated broadcasting functions
- Useful linear algebra, Fourier transform and random number functions

Now lets give numpy a try.

In [1]:
import numpy as np

### Array declaration in numpy
In mathematics, __[tensors](https://en.wikipedia.org/wiki/Tensor)__ are geometric object that describe linear relations between geometric vectors, scalars, and other tensors. We can see think of tensors as multidimensional arrays. Declaring tensor (array) object in numpy is easy.

In [2]:
a = np.array(1)  # rank 0 tensor (scalar)
b = np.array([1, 2, 3])   # rank 1 tensor (vector)
c = np.array([[1, 2, 3]])    # rank 2 tensor (matrix)
d = np.array([[1],[2],[3]])  # rank 2 tensor (matrix) 
e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  # rank 3 tensor (3-tensor)

Tensor rank can be determined by the length of the numpy array shape. 

In [3]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)
print(e.shape)

()
(3,)
(1, 3)
(3, 1)
(2, 2, 3)


Numpy has some useful array functions. For example we can easily create a matrix filled with zeros

In [4]:
np.zeros((3,2),dtype=np.int32)

array([[0, 0],
       [0, 0],
       [0, 0]])

Or an array with random numbers

In [5]:
np.random.rand(3,2)

array([[0.68508079, 0.33411916],
       [0.10375297, 0.21715967],
       [0.38900396, 0.30186872]])

### Element-wise operations in Numpy
It's very easy to manipulate matrix using numpy. 

In [6]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 3], [2, 1]])

In [7]:
print(a+b)
print(a*b)
print(a/b)
print(a**2)

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[0.25       0.66666667]
 [1.5        4.        ]]
[[ 1  4]
 [ 9 16]]


### Broadcasting functions in Numpy.

When you're doing repetitve computation for an array, you can take advantage of the numpy broadcasting functions. For example, numpy will find the matching dimension and fill in the blanks for you:

$$ \begin{bmatrix}1 & 2\\3 & 4\\5 & 6\end{bmatrix} + 2 = \begin{bmatrix}1+2 & 2+2\\3+2 & 4+2\\5+2 & 6+2\end{bmatrix} $$ 

$$ \begin{bmatrix}1 & 2\\3 & 4\\5 & 6\end{bmatrix} + \begin{bmatrix}1\\2\\3\end{bmatrix} = \begin{bmatrix}1+1 & 2+1\\3+2 & 4+2\\5+3 & 6+3\end{bmatrix} $$ 

$$ \begin{bmatrix}1 & 2\\3 & 4\\5 & 6\end{bmatrix} + \begin{bmatrix}1 & 2\end{bmatrix} = \begin{bmatrix}1+1 & 2+2\\3+1 & 4+2\\5+1 & 6+2\end{bmatrix} $$

( please note that the above equations don't hold true in a general mathematical sense, they just show you how numpy broadcasting function works )

In [8]:
a = np.array([[1,2], [3,4], [5,6]])

In [9]:
print(a+2)
print(a+[[1],[2],[3]])
print(a+[1,2])

[[3 4]
 [5 6]
 [7 8]]
[[2 3]
 [5 6]
 [8 9]]
[[2 4]
 [4 6]
 [6 8]]


### Nupmy indexing

Numpy indexing is very similar to python index (0-indexed).

In [10]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
print(a[2,1]) # Get an array element
print(a[2,1:3]) # Get a fraction of a column vector
print(a[:,0]) # Get a column vector
print(np.expand_dims(a[:,0], axis=1)) # Get a column vector and add a new axis
print(a[1,:]) # Get a row vector

10
[10 11]
[1 5 9]
[[1]
 [5]
 [9]]
[5 6 7 8]


### Matrix multiplication

Matrix math is at the heart of neural network computation. It is important that you're familiar with at least matrix multiplication before you start implementing a deep neural network.

$$ \begin{bmatrix}a_{11} & a_{21}\\a_{12} & a_{22}\\a_{13} & a_{23}\\a_{14} & a_{24}\end{bmatrix}\begin{bmatrix}b_{11} & b_{21} & b_{31}\\b_{12} & b_{22} & b_{32}\end{bmatrix} = \begin{bmatrix}a_{11}b_{11}+a_{21}b_{12} & a_{11}b_{21}+a_{21}b_{22} & a_{11}b_{31}+a_{21}b_{32}\\a_{12}b_{11}+a_{22}b_{12} & a_{12}b_{21}+a_{22}b_{22} & a_{12}b_{31}+a_{22}b_{32}\\a_{13}b_{11}+a_{23}b_{12} & a_{13}b_{21}+a_{23}b_{22} & a_{13}b_{31}+a_{23}b_{32}\\a_{14}b_{11}+a_{24}b_{12} & a_{14}b_{21}+a_{24}b_{22} &
a_{14}b_{31}+a_{24}b_{32}\end{bmatrix} $$

So this means : 
$$ \begin{bmatrix}1 & 2\\3 & 4\\5 & 6\\7 & 8\end{bmatrix}\begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\end{bmatrix} = \begin{bmatrix}1\times1+2\times4 & 1\times2+2\times5 & 1\times3+2\times6\\3\times1+4\times4 & 3\times2+4\times5 & 3\times3+4\times6\\5\times1+6\times4 & 5\times2+6\times5 & 5\times3+6\times6\\7\times1+8\times4 & 7\times2+8\times5 &
7\times3+8\times6\end{bmatrix} = \begin{bmatrix}9 & 12 & 5\\19 & 26 & 33\\29 & 40 & 51\\39 & 54 & 69\end{bmatrix}$$

Of course you don't want explicitly calculate matrix multiplication like this in a real program. This is just for understanding the math. Numpy can do this kind of low-level work for you. Before we jump into matrix math, let's get to know the basics of Numpy.

In [12]:
a = np.array([[1,2], [3,4], [5,6], [7,8]])
b = np.array([[1,2,3], [4,5,6]])
c = np.dot(a,b)

In [13]:
print(c)

[[ 9 12 15]
 [19 26 33]
 [29 40 51]
 [39 54 69]]


Sometimes it may become necessary to do the multiplication backwards(for example, during back propagation). B times A won't work because the dimension wouldn't match.

In [14]:
np.dot(b,a)

ValueError: shapes (2,3) and (4,2) not aligned: 3 (dim 1) != 4 (dim 0)

This is what we can do : $$ B^TA^T $$ and actually $$ (B^TA^T)^T = AB $$ We can easily find out in numpy:

In [15]:
np.dot(b.T, a.T).T

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51],
       [39, 54, 69]])

In [16]:
x = np.array((1,2,3))

In [17]:
y = x[:,None]

In [18]:
x.shape

(3,)

In [19]:
y.shape

(3, 1)

In [20]:
y = x[:,np.newaxis]

In [21]:
y.shape

(3, 1)

In [22]:
y

array([[1],
       [2],
       [3]])

In [23]:
z = y[:,np.newaxis,:]

In [24]:
z.shape

(3, 1, 1)

In [25]:
z = y[:,None,:]

In [26]:
z.shape

(3, 1, 1)